############################ WEBSTUFF ########################################

[[language]]
name = "html"
formatter = { command = 'npx', args = ["prettier", "--parser", "html"] }
auto-format = false

[[language]]
name = "css"
formatter = { command = 'npx', args = ["prettier", "--parser", "css"] }

[[language]]
name = "javascript"
formatter = { command = 'npx', args = ["prettier", "--parser", "typescript"] }
# auto-format = true

[[language]]
name = "typescript"
formatter = { command = 'npx', args = ["prettier", "--parser", "typescript"] }
# auto-format = true

[[language]]
name = "tsx"
formatter = { command = 'npx', args = ["prettier", "--parser", "typescript"] }
# auto-format = true

[[language]]
name = "jsx"
formatter = { command = 'npx', args = ["prettier", "--parser", "typescript"] }
# auto-format = true

############################ PYTHON ########################################

[[language]]
name = "python"
language-servers = ["pylsp", "basedpyright", "ruff"]
auto-format = false

[language-server.pylsp.config.pylsp]
plugins.pyls_mypy.enabled = true
plugins.pyls_mypy.live_mode = true

[language-server.rust-analyzer]
config = { cargo = { allFeatures = true } }

############################ TYPST ########################################

[language-server.tinymist]
command = "tinymist"

[[language]]
name = "typst"
language-servers = ["tinymist"]
