############################ WEBSTUFF ########################################

[[language]]
name = "html"
formatter = { command = 'npx', args = ["prettier", "--parser", "html"] }
auto-format = false

[[language]]
name = "css"
formatter = { command = 'npx', args = ["prettier", "--parser", "css"] }

[[language]]
name = "javascript"
formatter = { command = 'npx', args = ["prettier", "--parser", "typescript"] }
# auto-format = true

[[language]]
name = "typescript"
formatter = { command = 'npx', args = ["prettier", "--parser", "typescript"] }
# auto-format = true

[[language]]
name = "tsx"
formatter = { command = 'npx', args = ["prettier", "--parser", "typescript"] }
# auto-format = true

[[language]]
name = "jsx"
formatter = { command = 'npx', args = ["prettier", "--parser", "typescript"] }
# auto-format = true

############################ PYTHON ########################################

[[language]]
name = "python"
language-servers = ["pylsp", "basedpyright", "ruff"]
auto-format = false

[language-server.pylsp.config.pylsp]
plugins.pyls_mypy.enabled = true
plugins.pyls_mypy.live_mode = true

############################ RUST #########################################

[language-server.rust-analyzer]
config = { cargo = { allFeatures = true } }

############################ TYPST ########################################

[language-server.tinymist]
command = "tinymist"

[[language]]
name = "typst"
language-servers = ["tinymist", "ltex-ls-plus"]

########################## LTEX LS PLUS #################################

[language-server.ltex-ls-plus.config]
ltex.diagnosticSeverity = "warning"
ltex.ltex-ls.logLevel = "warning"
ltex.language = "en-GB"
ltex.disabledRules = { "en-GB" = ["PROFANITY"] }
ltex.dictionary = { "en-GB" = ["GiB"] }

# from GEA NB27
# [[language]]
# name = "python"
# language-id = "python"
# roots = ["pyproject.toml", ".venv/"]
# language-servers = ["basedpyright", "ruff"]
# auto-format = true
# formatter = { command = "uvx", args = ["ruff","format", "-" ] }
# file-types = ["py", "ipynb"]
# comment-token = "#"
# shebangs = ["python"]
# 
# [language-server.basedpyright]
# environment = { "LC_ALL" = "en_GB.UTF8" }
# command = "uv"
# args = ["run", "basedpyright-langserver", "--stdio"]
# required-root-patterns = ["pyproject.toml"]
# 
# [language-server.ruff]
# command = "uvx"
# args = ["ruff","server"]
# environment = { "RUFF_TRACE" = "messages" }
