[[language]]
name = "html"
formatter = { command = 'npx', args = ["prettier", "--parser", "html"] }
auto-format = false

[[language]]
name = "css"
formatter = { command = 'npx', args = ["prettier", "--parser", "css"] }

[[language]]
name = "javascript"
formatter = { command = 'npx', args = ["prettier", "--parser", "typescript"] }
# auto-format = true

[[language]]
name = "typescript"
formatter = { command = 'npx', args = ["prettier", "--parser", "typescript"] }
# auto-format = true

[[language]]
name = "tsx"
formatter = { command = 'npx', args = ["prettier", "--parser", "typescript"] }
# auto-format = true

[[language]]
name = "jsx"
formatter = { command = 'npx', args = ["prettier", "--parser", "typescript"] }
# auto-format = true
